#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 269546-web-01 	100.25.38.216:80 check
    server 269546-web-02 	54.157.159.148:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
